// ignore_for_file: constant_identifier_names

class DotEnvConstants {
  DotEnvConstants._();

  static const PWD_VALIDATION_RULE_MINIMUM_CHARACTER_COUNT =
      "PWD_VALIDATION_RULE_MINIMUM_CHARACTER_COUNT";
  static const PWD_VALIDATION_RULE_SPECIAL_LETTER =
      "PWD_VALIDATION_RULE_SPECIAL_LETTER";
  static const PWD_VALIDATION_RULE_LOWERCASE_LETTER =
      "PWD_VALIDATION_RULE_LOWERCASE_LETTER";
  static const PWD_VALIDATION_RULE_UPPERCASE_LETTER =
      "PWD_VALIDATION_RULE_UPPERCASE_LETTER";
  static const PWD_VALIDATION_RULE_NUMBER_COUNT =
      "PWD_VALIDATION_RULE_NUMBER_COUNT";
}
